# Generated by Django 3.2.7 on 2021-10-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='компаниия')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'компаниия',
                'verbose_name_plural': 'компаниии',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Игра')),
                ('description', models.TextField(max_length=350, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Изображение')),
                ('year', models.PositiveSmallIntegerField(default=2021, verbose_name='Год выхода')),
                ('country', models.CharField(max_length=15, verbose_name='Страна')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('company', models.ManyToManyField(to='base.Company', verbose_name='Компании')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Жанр')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Юзер')),
                ('text', models.TextField(max_length=250, verbose_name='Комментарий')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Комментрий')),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Юзер',
            },
        ),
        migrations.CreateModel(
            name='PersonGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(blank=True, verbose_name='Возраст')),
                ('race', models.CharField(default='Человек', max_length=30, verbose_name='Раса')),
                ('slug', models.SlugField(unique=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='GameShorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Кадр',
                'verbose_name_plural': 'Кадры',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='base.Genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='game',
            name='person',
            field=models.ManyToManyField(related_name='персонажи', to='base.PersonGame'),
        ),
    ]
