# Generated by Django 3.2.7 on 2021-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_game_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='persongame',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
