# Generated by Django 3.2.7 on 2021-10-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_persongame_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persongame',
            name='description',
            field=models.TextField(max_length=550, null=True, verbose_name='Описание'),
        ),
    ]
